# Generated by Django 2.0.5 on 2018-06-26 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('song_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default='000000', max_length=1000),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
    ]
