# Generated by Django 2.0.5 on 2018-08-25 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rooms', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('arr_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('dep_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
